Samples/Workflow.CallCustomService/Workflow.CallCustomServiceWeb/Controllers/DataController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Http;
using Workflow.CallCustomServiceWeb.Northwind;
using Workflow.CallCustomServiceWeb.Services;

namespace Workflow.CallCustomServiceWeb.Controllers
{
    public class DataController : ApiController
    {
        public void Post([FromBody]string country)
        {
            var supplierNames = GetSupplierNames(country);
            UpdateSuppliers(country, supplierNames);
        }

        private string[] GetSupplierNames(string country)
        {
            Uri uri = new Uri("http://services.odata.org/V3/Northwind/Northwind.svc");
            var entities = new NorthwindEntities(uri);
            var names = entities.Suppliers
                .Where(s => s.Country == country)
                .AsEnumerable()
                .Select(s => s.CompanyName)
                .ToArray();
            return names;
        }

        private void UpdateSuppliers(string country, string[] supplierNames)
        {
            var request = HttpContext.Current.Request;
            var authority = request.Url.Authority;
            var spAppWebUrl = request.Headers["SPAppWebUrl"];
            var contextToken = request.Headers["SPContextToken"];

            using (var clientContext = TokenHelper.GetClientContextWithContextToken(
                spAppWebUrl, contextToken, authority))
            {
                var service = new PartSuppliersService(clientContext);
                service.UpdateSuppliers(country, supplierNames);
            }
        }
    }
}

Samples/Workflow.CallCustomService/Workflow.CallCustomServiceWeb/Controllers/HomeController.cs
using System.Web.Mvc;
using Workflow.CallCustomServiceWeb.Services;

namespace Workflow.CallCustomServiceWeb.Controllers
{
    public class HomeController : Controller
    {
        [SharePointContextFilter]
        public ActionResult Index()
        {
            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            ViewBag.AppWebUrl = spContext.SPAppWebUrl.ToString();
            return View();
        }
    }
}

Samples/Workflow.CallCustomService/Workflow.CallCustomServiceWeb/Controllers/PartSuppliersController.cs
using Microsoft.SharePoint.Client;
using Microsoft.SharePoint.Client.WorkflowServices;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Web.Mvc;
using Workflow.CallCustomServiceWeb.Services;

namespace Workflow.CallCustomServiceWeb.Controllers
{
    public class PartSuppliersController : Controller
    {
        public ActionResult CreateGet(string spHostUrl)
        {
            ViewBag.Country = new SelectListItem[] {
                new SelectListItem { Text = "Australia", Value="Australia" },
                new SelectListItem { Text = "Canada", Value="Canada" },
                new SelectListItem { Text = "Finland", Value="Finland" },
                new SelectListItem { Text = "USA", Value="USA" }
            };

            if (ControllerContext.IsChildAction) return PartialView("Create");
            return PartialView("Create");
        }

        [HttpPost]
        [SharePointContextFilter]
        public ActionResult Create(string country, string spHostUrl)
        {
            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPAppWeb())
            {
                var service = new PartSuppliersService(clientContext);
                var id = service.GetIdByCountry(country);
                if (id == null)
                {
                    id = service.Add(country);
                    TempData["Message"] = "Part Supplier Successfully Created!";
                }
                else
                    TempData["ErrorMessage"] = string.Format("Failed to Create The Part Supplier: There's already a Part Supplier who's country is {0}.", country);

                return RedirectToAction("Details", new { id = id.Value, SPHostUrl = spHostUrl });
            }
        }

        [HttpPost]
        [SharePointContextFilter]
        public ActionResult StartWorkflow(int id, Guid workflowSubscriptionId, string spHostUrl)
        {
            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext) as SharePointAcsContext;

            var webServiceUrl = Url.RouteUrl("DefaultApi", new { httproute = "", controller = "Data" }, Request.Url.Scheme);
            var payload = new Dictionary<string, object>
                {
                    { "appWebUrl", spContext.SPAppWebUrl.ToString() },
                    { "webServiceUrl", webServiceUrl },
                    { "contextToken",  spContext.ContextToken }
                };

            using (var clientContext = spContext.CreateUserClientContextForSPAppWeb())
            {
                var service = new PartSuppliersService(clientContext);
                service.StartWorkflow(workflowSubscriptionId, id, payload);
            }

            TempData["Message"] = "Workflow Successfully Started!";
            return RedirectToAction("Details", new { id = id, SPHostUrl = spHostUrl });
        }

        [HttpPost]
        [SharePointContextFilter]
        public ActionResult PublishSubmitEvent(int id, Guid workflowInstanceId, string spHostUrl)
        {
            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPAppWeb())
            {
                var service = new PartSuppliersService(clientContext);
                service.PublishCustomEvent(workflowInstanceId, "Submit for Approval", "");
                
                // Wait until workflow user status changed
                WorkflowInstance instance;
                do
                {
                    Thread.Sleep(1000);
                    instance = service.GetWorkflowInstance(workflowInstanceId);
                }
                while (instance.UserStatus == "Wait for Submit");
            }
            TempData["Message"] = "Successfully Submitted For Approval!";


            return RedirectToAction("Details", new { id = id, SPHostUrl = spHostUrl });
        }

        [SharePointContextFilter]
        public ActionResult Details(int id)
        {
            var spContext = SharePointContextProvider.Current.GetSharePointContext(HttpContext);
            using (var clientContext = spContext.CreateUserClientContextForSPAppWeb())
            {
                var service = new PartSuppliersService(clientContext);
                var item = service.GetItem(id);
                if (item == null) return HttpNotFound();

                var workflowSubscription = service.GetWorkflowSubscription("Approve Suppliers");

                ViewBag.AppWebUrl = spContext.SPAppWebUrl.ToString();
                ViewBag.WorkflowSubscription = workflowSubscription;
                ViewBag.WorkflowInstance = service.GetItemWorkflowInstance(workflowSubscription.Id, id);
                ViewBag.ApprovalTask = service.GetApprovalTaskForCurrentUser(id);

                return View(item);
            }
        }
    }
}

Samples/Workflow.CallCustomService/Workflow.CallCustomServiceWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Workflow - CallCustomServiceWeb";
    string appWebUrl = ViewBag.AppWebUrl as string;
}

<div>
    <h2>App Web List</h2>
    <p>Click the link below to view the Part Suppliers List</p>
    <h5><a href="@(appWebUrl)Lists/Part Suppliers" target="_blank">Part Suppliers</a></h5>
</div>
<div>
    <h2>Create a Part Supplier</h2>
    @Html.Action("CreateGet", "PartSuppliers")
</div>

@section scripts{
    <script type="text/javascript">
        function chromeLoaded() {
            $('#chromeControl_bottomheader').remove();
            $('body').show();
        }

        //function callback to render chrome after SP.UI.Controls.js loads
        function renderSPChrome() {
            //Set the chrome options
            var options = {
                'appTitle': "@ViewBag.Title",
                'onCssLoaded': 'chromeLoaded()'
            };

            //Load the Chrome Control in the chrome_ctrl_placeholder element of the page
            var chromeNavigation = new SP.UI.Controls.Navigation('chrome_ctrl_placeholder', options);
            chromeNavigation.setVisible(true);
        }
    </script>
}

Samples/Workflow.CallCustomService/Workflow.CallCustomServiceWeb/Views/PartSuppliers/Create.cshtml
@using (Html.BeginForm("Create", "PartSuppliers", new { SPHostUrl = Request["SPHostUrl"] },
    FormMethod.Post, new { id = "createPartSuppliers", target = "_blank", role = "form" }))
{
    <div class="form-group">
        <label for="country">Choose a country for the Part Supplier.</label>
        @Html.DropDownList("country", null, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn">Create</button>
}

Samples/Workflow.CallCustomService/Workflow.CallCustomServiceWeb/Views/PartSuppliers/Details.cshtml
@using Microsoft.SharePoint.Client
@using Microsoft.SharePoint.Client.WorkflowServices
@model ListItem
@{
    ViewBag.Title = "Part Supplier";
    var appWebUrl = ViewBag.AppWebUrl as string;
    var workflowSubscription = ViewBag.WorkflowSubscription as WorkflowSubscription;
    var workflowInstance = ViewBag.WorkflowInstance as WorkflowInstance;
    var approvalTask = ViewBag.ApprovalTask as ListItem;

    var spHostUrl = Request["SPHostUrl"];

    var startWorkflowBtnEnabled = workflowInstance == null;
    var submitForApproveBtnEnabled = workflowInstance != null && workflowInstance.UserStatus == "Wait for Submit";
    var approveBtnEnabled = approvalTask != null && ((string)approvalTask["Status"]) == "Not Started";
}

<h2>Part Suppliers</h2>

<dl class="dl-horizontal">
    <dt>Id</dt>
    <dd>@Model["ID"]</dd>
    <dt>Country</dt>
    <dd>@Model["Country"]</dd>
    <dt>Suppliers</dt>
    <dd>@Model["Suppliers"]&nbsp;</dd>
    <dt>IsApproved</dt>
    <dd>@Model["IsApproved"]&nbsp;</dd>
    <dt>User Status</dt>
    <dd>@(workflowInstance != null ? workflowInstance.UserStatus : "")&nbsp;</dd>
</dl>

<div id="actions">
    @using (Html.BeginForm("Details", "PartSuppliers", new { id = Model.Id }, FormMethod.Get, null))
    {
        <input type="hidden" name="SPHostUrl" value="@spHostUrl" />
        <button type="submit" class="btn">Refresh</button>
    }

    @using (Html.BeginForm("StartWorkflow", "PartSuppliers", new { SPHostUrl = spHostUrl }, FormMethod.Post, null))
    {
        if (startWorkflowBtnEnabled)
        {
            <input type="hidden" name="id" value="@Model.Id" />
            <input type="hidden" name="workflowSubscriptionId" value="@workflowSubscription.Id" />
            <button type="submit" class="btn">Start Workflow</button>
        }
        else
        {
            <button type="submit" class="btn" disabled="disabled">Start Workflow</button>
        }
    }

    @using (Html.BeginForm("PublishSubmitEvent", "PartSuppliers", new { SPHostUrl = spHostUrl }, FormMethod.Post, null))
    {
        if (submitForApproveBtnEnabled)
        {
            <input type="hidden" name="id" value="@Model.Id" />
            <input type="hidden" name="workflowInstanceId" value="@workflowInstance.Id" />
            <button type="submit" class="btn">Submit for Approval</button>
        }
        else
        {
            <button type="submit" class="btn" disabled="disabled">Submit for Approval</button>
        }
    }

    <form action="@(appWebUrl)Lists/WorkflowTaskList/EditForm.aspx" method="get">
        @if (approveBtnEnabled)
        {
            <input type="hidden" name="ID" value="@approvalTask.Id" />
            <input type="hidden" name="Source" value="@Request.Url.OriginalString" />
            <button type="submit" class="btn">Approve</button>
        }
        else
        {
            <button type="submit" class="btn" disabled="disabled">Approve</button>
        }
    </form>
</div>

<h2>Instruction</h2>
<div>
    <ol>
        <li>Click <span class="ref">Start Workflow</span> to start the workflow. The workflow will get suppliers from the <a href="http://services.odata.org/V3/Northwind/Northwind.svc/Suppliers" target="_blank">Northwind OData service</a> and then update the current Part Supplier list item.</li>
        <li>It takes a while for the workflow to finish the two jobs. Click <span class="ref">Refresh</span> until <span class="ref">Submit for Approval</span> is enabled.</li>
        <li>Now, the workflow is suspended. Click <span class="ref">Submit for Approval</span> to resume the workfow. The workflow will start an approval task.</li>
        <li>Click <span class="ref">Refresh</span> until <span class="ref">Approve</span> is enabled.</li>
        <li>Click <span class="ref">Approve</span>, the browser will navigate you to the approval page.</li>
    </ol>
</div>

@section scripts{
    <script type="text/javascript">
        function chromeLoaded() {
            $('#chromeControl_bottomheader').remove();
            $('body').show();
        }

        //function callback to render chrome after SP.UI.Controls.js loads
        function renderSPChrome() {
            //Set the chrome options
            var options = {
                'appTitle': "@ViewBag.Title",
                'onCssLoaded': 'chromeLoaded()'
            };

            //Load the Chrome Control in the chrome_ctrl_placeholder element of the page
            var chromeNavigation = new SP.UI.Controls.Navigation('chrome_ctrl_placeholder', options);
            chromeNavigation.setVisible(true);
        }
    </script>
}